version: "3.7"

services:
  scep:
    image: scep
    # image: <my account>.dkr.ecr.<my region>.amazonaws.com/akff-web
    volumes:
      - ./config/certs/depot:/service/scep/depot
    build:
      context: .
      dockerfile: ./images/scep/Dockerfile
      args:
        - SCEP_VERSION=2.1.0
        - CHALLENGE=ThisIsAChallenge
        - ALLOW_RENEW=0
    ports:
      - "8080:8080"

  nanomdm:
    container_name: nanomdm
    image: nanomdm
    volumes:
      - ../config/certs/depot/ca.pem:/service/nanomdm/ca.pem
    build:
      context: .
      dockerfile: ./images/nanomdm/Dockerfile
      args:
        - NANOMDM_VERSION=0.2.0
        - API_KEY=nanomdm
    ports:
      - "9000:9000"

    depends_on:
      - scep
  micro2nano:
    image: micro2nano
    # image: <my account>.dkr.ecr.<my region>.amazonaws.com/akff-web
    build:
      context: .
      dockerfile: ./images/micro2nano/Dockerfile
      args:
        - VERSION=0.2.0
        - API_KEY=nanomdm
        - NANO_API_KEY=nanomdm
        - NANO_URL=http://127.0.0.1:9000/v1/enqueue
    ports:
      - "9001:9001"
    depends_on:
      - nanomdm

